# Generated by Django 5.2.7 on 2026-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='eff_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='EFF Value'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='ter_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='TER Value'),
        ),
    ]
