# Generated by Django 5.2.7 on 2026-01-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0002_alter_psrproject_eff_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='ebit_percentage',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='EBIT (%)'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='sgna_percentage',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='SGNA (%)'),
        ),
    ]
