# Generated by Django 5.2.7 on 2026-02-02 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0004_alter_psrproject_project_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_procurement_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('expected_receive_date', models.DateField()),
                ('actual_receive_date', models.DateField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, help_text="Percentage of the project's sales_value (e.g. 30.00 for 30%)", max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: percentage × project.sales_value', max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Additional details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='psr.psrproject')),
            ],
            options={
                'verbose_name': 'Project Payment Milestone',
                'verbose_name_plural': 'Project Payment Milestones',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
