# Generated by Django 5.2.7 on 2026-02-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0005_alter_psrproject_project_manager_projectpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='projectpayment',
            name='amount_in_foreign_curr',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated: percentage x project.sales_value_foreign_curr', max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, help_text="Percentage of the project's sales_value_foreign_curr (e.g. 30.00 for 30%)", max_digits=5),
        ),
    ]
