# Generated by Django 5.2.7 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0006_remove_projectpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='amount_in_foreign_curr',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
