# Generated by Django 5.2.7 on 2026-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0007_alter_projectpayment_amount_in_foreign_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
