# Generated by Django 5.2.7 on 2026-02-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0008_alter_projectpayment_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpayment',
            options={'verbose_name': 'Project Payment Milestone', 'verbose_name_plural': 'Project Payment Milestones'},
        ),
    ]
