# Generated by Django 5.2.7 on 2026-02-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0009_alter_projectpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='recieved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
