# Generated by Django 5.2.7 on 2026-02-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0010_projectpayment_recieved_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpayment',
            old_name='recieved_amount',
            new_name='received_amount',
        ),
    ]
