# Generated by Django 5.2.7 on 2026-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0011_rename_recieved_amount_projectpayment_received_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
