# Generated by Django 5.2.7 on 2026-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0012_alter_projectpayment_received_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrproject',
            name='risk',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Risk Value'),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='risk_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
