# Generated by Django 5.2.7 on 2026-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0013_psrproject_risk_psrsnapshot_risk_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='ebit_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, verbose_name='EBIT (%)'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='eff_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, verbose_name='EFF Value'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='sgna_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, verbose_name='SGNA (%)'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='ter_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, verbose_name='TER Value'),
        ),
    ]
