# Generated by Django 5.2.7 on 2026-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0014_alter_psrproject_ebit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='hk',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
    ]
