# Generated by Django 5.2.7 on 2026-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0015_alter_psrproject_hk'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrproject',
            name='hk2',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AddField(
            model_name='psrproject',
            name='sk_value',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='actual_budget',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='cost_with_sgna',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='direct_margin_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='direct_margin_value',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='ebit_percentage',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='ebit_value',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='eff_value',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='hk',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='risk',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, verbose_name='Risk Value'),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='sgna_value',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
        migrations.AlterField(
            model_name='psrproject',
            name='ter_value',
            field=models.DecimalField(decimal_places=20, default=0.0, editable=False, max_digits=30),
        ),
    ]
