# Generated by Django 5.2.7 on 2026-02-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0016_psrproject_hk2_psrproject_sk_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrsnapshot',
            name='ebit_percentage',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='ebit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
