# Generated by Django 5.2.7 on 2026-02-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0017_psrsnapshot_ebit_percentage_psrsnapshot_ebit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrsnapshot',
            name='net_marginal_income',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
