# Generated by Django 5.2.7 on 2026-02-09 12:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0019_psrsnapshot_net_marginal_income_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOKOActualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Reason for manual adjustment of SOKO actuals')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_cost_category', models.ForeignKey(limit_choices_to={'cost_category__code': 'SOKO'}, on_delete=django.db.models.deletion.CASCADE, related_name='soko_actual_adjustments', to='psr.projectcostcategory')),
            ],
            options={
                'verbose_name': 'SOKO Actual Adjustment',
                'verbose_name_plural': 'SOKO Actual Adjustments',
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='SOKOActualAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='psr.sokoactualadjustment')),
            ],
            options={
                'verbose_name': 'SOKO Actual Line',
                'verbose_name_plural': 'SOKO Actual Lines',
            },
        ),
    ]
