# Generated by Django 5.2.7 on 2026-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0020_sokoactualadjustment_sokoactualadjustmentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='invoice_no',
            field=models.CharField(max_length=100),
        ),
    ]
