# Generated by Django 5.2.7 on 2026-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0021_alter_projectpayment_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='amount_in_foreign_curr',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
    ]
