# Generated by Django 5.2.7 on 2026-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0022_alter_projectpayment_amount_in_foreign_curr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpayment',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
