# Generated by Django 5.2.7 on 2026-02-18 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0023_alter_projectpayment_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psrproject',
            name='sales_value_foreign_curr',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
