# Generated by Django 5.1.4 on 2026-02-19 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0024_alter_psrproject_sales_value_foreign_curr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSRProjectCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING_APPROVERS', 'Pending Approvers'), ('PENDING_ADMIN', 'Pending Admin'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_APPROVERS', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_request', to='psr.psrproject')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
