# Generated by Django 5.1.4 on 2026-02-19 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0025_psrprojectcreationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSRProjectApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('APPROVER', 'Approver'), ('ADMIN', 'Admin')], max_length=20)),
                ('action', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10, null=True)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='psr.psrprojectcreationrequest')),
            ],
            options={
                'unique_together': {('request', 'approver', 'stage')},
            },
        ),
    ]
