# Generated by Django 4.2 on 2026-03-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0026_psrprojectapprovalaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(db_index=True, help_text='CONo', max_length=20)),
                ('grr_no', models.CharField(db_index=True, help_text='GRRNo', max_length=100)),
                ('po_no', models.CharField(blank=True, help_text='PoNo', max_length=50)),
                ('grr_date', models.DateField(blank=True, help_text='Po.Date', null=True)),
                ('item_code', models.CharField(blank=True, help_text='ItemCode', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('supplier_name', models.CharField(blank=True, help_text='SupplierName', max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate', max_digits=18, null=True)),
                ('received_qty', models.DecimalField(blank=True, decimal_places=2, help_text='ReceivedQty', max_digits=18, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GRR Entry (Raw)',
                'verbose_name_plural': 'GRR Entries (Raw)',
            },
        ),
        migrations.CreateModel(
            name='PCRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_no', models.CharField(db_index=True, help_text='CONo', max_length=20)),
                ('pcr_no', models.CharField(db_index=True, help_text='PCRNo', max_length=100)),
                ('po_no', models.CharField(blank=True, help_text='PoNo', max_length=50)),
                ('pcr_date', models.DateField(blank=True, help_text='Po.Date', null=True)),
                ('item_code', models.CharField(blank=True, help_text='ItemCode', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('supplier_name', models.CharField(blank=True, help_text='SupplierName', max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate', max_digits=18, null=True)),
                ('recp_qty', models.DecimalField(blank=True, decimal_places=2, help_text='ReceivedQty', max_digits=18, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PCR Entry (Raw)',
                'verbose_name_plural': 'PCR Entries (Raw)',
            },
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='total_grr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='psrsnapshot',
            name='total_pcr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddIndex(
            model_name='pcrdata',
            index=models.Index(fields=['co_no'], name='psr_pcrdata_co_no_4bb8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='pcrdata',
            index=models.Index(fields=['pcr_no'], name='psr_pcrdata_pcr_no_042b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='pcrdata',
            index=models.Index(fields=['co_no', 'pcr_no'], name='psr_pcrdata_co_no_b11c80_idx'),
        ),
        migrations.AddIndex(
            model_name='grrdata',
            index=models.Index(fields=['co_no'], name='psr_grrdata_co_no_0a2bad_idx'),
        ),
        migrations.AddIndex(
            model_name='grrdata',
            index=models.Index(fields=['grr_no'], name='psr_grrdata_grr_no_e42e75_idx'),
        ),
        migrations.AddIndex(
            model_name='grrdata',
            index=models.Index(fields=['co_no', 'grr_no'], name='psr_grrdata_co_no_c30101_idx'),
        ),
    ]
