# Generated by Django 4.2 on 2026-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0027_grrdata_pcrdata_psrsnapshot_total_grr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrsnapshot',
            name='poc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
