# Generated by Django 5.2.10 on 2026-01-30 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
        ('purchase', '0002_alter_project_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('project', 'department'), name='unique_project_department'),
        ),
    ]
