# Generated by Django 5.2.10 on 2026-01-30 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('purchase', '0003_project_unique_project_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_projects', to='accounts.department'),
        ),
    ]
