# Generated by Django 5.2.10 on 2026-01-30 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('psr', '0001_initial'),
        ('purchase', '0004_alter_project_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True)), fields=('project',), name='unique_project_only_when_dept_null'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', True)), fields=('department',), name='unique_dept_only_when_project_null'),
        ),
    ]
