# Generated by Django 5.2.10 on 2026-01-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_project_unique_project_only_when_dept_null_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termassignment',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_term_assignments', to='purchase.supplier'),
            preserve_default=False,
        ),
    ]
