# Generated by Django 5.2.10 on 2026-02-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('purchase', '0006_termassignment_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementupload',
            old_name='approved_by',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='procurementupload',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='procurementupload',
            name='excel',
        ),
        migrations.RemoveField(
            model_name='procurementupload',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='procurementupload',
            name='attachment',
            field=models.FileField(default='', upload_to='procurement_excel/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementupload',
            name='pb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.projectboard'),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model__in', ['projectboard', 'commercialrequirement', 'supplier', 'suppliernegotiation', 'lineitem', 'lineitemnegotiation', 'termassignment'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
