# Generated by Django 4.2 on 2026-02-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_approved_by_procurementupload_uploaded_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfile',
            name='upload_session',
        ),
        migrations.RemoveField(
            model_name='procurementupload',
            name='project',
        ),
    ]
