# Generated by Django 4.2 on 2026-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_remove_excelfile_upload_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcondition',
            name='condition_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='termcondition',
            unique_together={('term', 'condition_name')},
        ),
    ]
