# Generated by Django 4.2 on 2026-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_termcondition_condition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='item_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='commodity_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
