# Generated by Django 5.2.12 on 2026-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_excelfile_item_budget_projectboard_commodity_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(choices=[('Pcs', 'Pcs'), ('Meter', 'Meter'), ('Set', 'Set'), ('Liter', 'Liter'), ('Days', 'Days'), ('Hrs', 'Hrs'), ('Nos', 'Nos')], max_length=50),
        ),
    ]
