# Generated by Django 5.2.12 on 2026-03-13 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('psr', '0026_psrprojectapprovalaction'),
        ('purchase', '0011_alter_lineitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_department',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_only_when_dept_null',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_dept_only_when_project_null',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project',), name='unique_project_entry'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('department', 'project_type'), name='unique_dept_type_combo'),
        ),
    ]
