# Generated by Django 5.2.10 on 2026-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulepermission',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
