# Generated by Django 5.2.10 on 2026-01-28 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_working_hours_per_week', models.PositiveIntegerField(default=45)),
            ],
            options={
                'verbose_name': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('budgeted_hours', models.PositiveIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, help_text='Special conditions, contacts, warnings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='For UI sorting')),
                ('icon_text', models.CharField(blank=True, help_text="Short text/icon for UI (e.g. 'DE', 'PE')", max_length=50)),
                ('level', models.PositiveIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='capacity_planning.department')),
            ],
            options={
                'verbose_name': 'Department',
                'ordering': ['order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_code', models.CharField(blank=True, help_text='e.g. PRJ-2025-001', max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('QUOTED', 'Quoted'), ('PLANNED', 'Planned'), ('ORDERED', 'Ordered')], default='QUOTED', max_length=20)),
                ('total_manhours', models.PositiveIntegerField(blank=True, help_text='Overall estimated total effort (optional global value)', null=True)),
                ('allotted_weeks', models.PositiveIntegerField(blank=True, help_text='Overall planned duration in weeks (optional global value)', null=True)),
                ('start_monday', models.DateField(blank=True, help_text='Global start (Monday) – optional', null=True)),
                ('end_monday', models.DateField(blank=True, help_text='Global end (Monday) – optional', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code for UI (e.g., #1e90ff)', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_monday'],
            },
        ),
        migrations.CreateModel(
            name='ProjectWeekAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_monday', models.DateField(db_index=True)),
                ('manhours', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_weeks', to='capacity_planning.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_weeks', to='capacity_planning.project')),
            ],
            options={
                'verbose_name': 'Planned Weekly Demand',
                'ordering': ['week_monday'],
                'unique_together': {('project', 'department', 'week_monday')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('TL', 'Team Lead'), ('PEM', 'Project Engineer Manager'), ('SIM', 'Simulation Engineer'), ('DES', 'Designer'), ('PLC', 'PLC Engineer'), ('ROB', 'Robotics Engineer'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('emp_id', models.CharField(blank=True, help_text='Employee ID from HR system (e.g. EMP001, 12345)', max_length=50, null=True, unique=True)),
                ('is_internal', models.BooleanField(default=True, help_text='Uncheck for freelancers/contractors')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Only for externals – overrides supplier rate', max_digits=8, null=True)),
                ('availability_per_week', models.PositiveIntegerField(blank=True, help_text='Override default availability from AppSettings', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joining_date', models.DateField(blank=True, help_text='Date the resource joined the company', null=True)),
                ('leaving_date', models.DateField(blank=True, help_text='Date the resource leaves the company', null=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this resource can work in', related_name='resources', to='capacity_planning.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_resources', to='capacity_planning.supplier')),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDepartmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_manhours', models.PositiveIntegerField(help_text='Estimated manhours for this department')),
                ('allotted_weeks', models.PositiveIntegerField(help_text='Allotted weeks for this department')),
                ('start_monday', models.DateField(help_text="Start Monday for this department's scope")),
                ('end_monday', models.DateField(blank=True, help_text="End Monday for this department's scope", null=True)),
                ('status', models.CharField(choices=[('QUOTED', 'Quoted'), ('PLANNED', 'Planned'), ('ORDERED', 'Ordered')], default='QUOTED', help_text="Status specific to this department's work", max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='capacity_planning.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_allocations', to='capacity_planning.project')),
            ],
            options={
                'verbose_name': 'Project-Department Allocation',
                'verbose_name_plural': 'Project-Department Allocations',
                'unique_together': {('project', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('week_monday', models.DateField(db_index=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='capacity_planning.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='capacity_planning.project')),
                ('week_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='capacity_planning.projectweekallocation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='capacity_planning.resource')),
            ],
            options={
                'ordering': ['-week_monday'],
                'unique_together': {('resource', 'project', 'department', 'week_monday')},
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_monday', models.DateField(db_index=True)),
                ('hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(45)])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='capacity_planning.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_planning.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacity_planning.resource')),
                ('week_allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='capacity_planning.projectweekallocation')),
            ],
            options={
                'verbose_name': 'Weekly Resource Allocation',
                'indexes': [models.Index(fields=['week_monday'], name='capacity_pl_week_mo_6e76f2_idx')],
                'unique_together': {('resource', 'project', 'department', 'week_monday')},
            },
        ),
        migrations.CreateModel(
            name='ExternalCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_monday', models.DateField(db_index=True)),
                ('hours', models.PositiveIntegerField(default=0, help_text='Weekly hours this supplier can provide for this project (external capacity)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_capacities', to='capacity_planning.project')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_capacities', to='capacity_planning.supplier')),
            ],
            options={
                'verbose_name_plural': 'External Capacities (Supplier-Project Level)',
                'ordering': ['-week_monday'],
                'unique_together': {('supplier', 'project', 'week_monday')},
            },
        ),
    ]
