# Generated by Django 5.2.10 on 2026-01-30 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('capacity_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceallocation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='projectdepartmentallocation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='projectweekallocation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_weeks', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this resource can work in', related_name='resources', to='accounts.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
