# Generated by Django 5.2.10 on 2026-01-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_planning', '0002_alter_resourceallocation_department_and_more'),
        #('psr', '0007_alter_psrproject_ebit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='psr_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacity_entries', to='psr.psrproject', verbose_name='PSR Project'),
        ),
    ]
