# Generated by Django 5.2.10 on 2026-01-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_planning', '0003_project_psr_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='psr_project',
        ),
    ]
