# Generated by Django 4.2 on 2026-02-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('capacity_planning', '0004_remove_project_psr_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcapacity',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_capacities_dept', to='accounts.department'),
        ),
    ]
