# Generated by Django 4.2 on 2026-02-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_department'),
        ('capacity_planning', '0005_externalcapacity_dept'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalcapacity',
            unique_together={('supplier', 'project', 'dept', 'week_monday')},
        ),
    ]
