# Generated by Django 5.2.12 on 2026-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_planning', '0006_alter_externalcapacity_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcapacity',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes for this capacity record', null=True),
        ),
    ]
