# Generated by Django 5.2.12 on 2026-03-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacity_planning', '0007_externalcapacity_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalcapacity',
            name='notes',
        ),
    ]
